# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pufin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('class_of', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('grade', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pin', models.DecimalField(decimal_places=0, max_digits=4)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
