# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufin', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='class_of',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
