# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pufin', '0009_userinfo_sha_256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='upload',
        ),
    ]
