# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pufin', '0010_remove_userinfo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pufin',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
